version: 2.1

jobs: 

  build-frontend: 
    docker: 
      image: circleci/node:13.8.0
    steps: 
      - checkout
      - run: |
          cd frontend
          npm install
          npm run build

  build-backend:
    docker:
      image: circleci/node:13.8.0
    steps:
      - checkout
      - run: |
          cd frontend
          npm install
          npm run build

workflows:
  build_and_test:
    jobs:
      - build-frontend
      - build-backend
